// Types and helpers for public/train-volume.json (generated by
// scripts/03-train-volume.ts from LTA tap-in/tap-out data).

export interface HourlyVolume {
  in: number[]; // 24 slots, index = hour of day, monthly totals
  out: number[];
}

export interface StationVolume {
  name: string;
  weekday: HourlyVolume;
  weekend: HourlyVolume;
}

export interface TrainVolume {
  yearMonth: string;
  dayCounts: { weekday: number; weekend: number };
  stations: Record<string, StationVolume>;
}

export type DayType = "weekday" | "weekend";

// One heat reading for one station at the selected hour.
export interface HeatPoint {
  t: number; // 0..1 normalized intensity (sqrt-scaled)
  in: number; // avg tap-ins per day for this hour
  out: number;
  name: string;
}

// Trains don't run 1am–5am, so the slider walks 05:00 → 23:00 → midnight.
export const SERVICE_HOURS = [
  5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0,
];

export function hourLabel(hour: number): string {
  return `${String(hour).padStart(2, "0")}:00`;
}

// Sequential blue ramp (dark-surface steps 700→100): near-zero recedes into
// the dark map, peak load reads bright.
const HEAT_RAMP = ["#0d366b", "#1c5cab", "#3987e5", "#86b6ef", "#cde2fb"];

const RAMP_RGB = HEAT_RAMP.map((hex) => [
  parseInt(hex.slice(1, 3), 16),
  parseInt(hex.slice(3, 5), 16),
  parseInt(hex.slice(5, 7), 16),
]);

export const HEAT_GRADIENT_CSS = `linear-gradient(to right, ${HEAT_RAMP.join(", ")})`;

export function heatColor(t: number): string {
  const c = Math.min(1, Math.max(0, t));
  const pos = c * (RAMP_RGB.length - 1);
  const i = Math.min(RAMP_RGB.length - 2, Math.floor(pos));
  const f = pos - i;
  const [r, g, b] = RAMP_RGB[i].map((v, k) =>
    Math.round(v + (RAMP_RGB[i + 1][k] - v) * f)
  );
  return `rgb(${r},${g},${b})`;
}

// Highest per-day (tap-in + tap-out) hourly load across all stations, hours
// and day types — the fixed top of the heat scale, so the animation shows
// absolute change over the day rather than re-normalizing per hour.
export function maxHourlyLoad(volume: TrainVolume): number {
  let max = 0;
  for (const st of Object.values(volume.stations)) {
    for (const dayType of ["weekday", "weekend"] as const) {
      const days = volume.dayCounts[dayType];
      for (let h = 0; h < 24; h++) {
        const load = (st[dayType].in[h] + st[dayType].out[h]) / days;
        if (load > max) max = load;
      }
    }
  }
  return max;
}

export function formatCount(n: number): string {
  if (n >= 10000) return `${Math.round(n / 1000)}k`;
  if (n >= 1000) return `${(n / 1000).toFixed(1)}k`;
  return String(Math.round(n));
}
